### ISSUE TITLE
Staked tokens not shown on manage candidate page

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-client#15]
![image](https://user-images.githubusercontent.com/344748/73358159-6799e580-4274-11ea-9d5f-7ceda17bfdfe.png)

**Comment by michaeljyeates** [comment]
Technically this is correct, it is showing tokens staked in the token contract.  We need to migrate the existing custodian locked tokens to be staked rather than deposited in the custodian contract.

This fixes the bug about custodians not being unable to vote and will remove some of the ui issues with reclaiming your stake

**Comment by lukestokes** [comment]
If we migrated these tokens today prior to updating the existing client, it wouldn't correct, yes? So the token migration is now a launch requirement for the new member client deployment, yes (along with updated contracts)?

When do you think we can do this and will we have to involve the custodians for all the individual transfers or do you plan to add a temporary active key to dacauthority?
