### ISSUE TITLE
Error approving msig with Anchor Mobile

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-client#51]
It works fine in Anchor Desktop, but on mobile I get this:

![IMG_4938](https://user-images.githubusercontent.com/344748/85584286-000e7900-b60d-11ea-91e4-f3983af78327.PNG)
![IMG_4939](https://user-images.githubusercontent.com/344748/85584290-013fa600-b60d-11ea-90f7-6f3803bf9cb5.PNG)

I upgraded to the latest, but still got this:

![IMG_4941](https://user-images.githubusercontent.com/344748/85585286-ddc92b00-b60d-11ea-99bb-b09658e55f79.PNG)

I'll check with Anchor to see if that's an issue on their side or something we need to fix on our end.

**Comment by aaroncox** [comment]
We're looking into it, I think the issue is on our end.

**Comment by aaroncox** [comment]
The issue was on our end in the mobile build of Anchor not support the bytes/binary data type as defined in the eosio.msig ABI.

We have an internal fix ready and this should be resolved in our next build.

**Comment by str** [comment]
@aaroncox , do you have an issue on your end to track?

**Comment by aaroncox** [comment]
We don't have a public tracker for it currently, no. 

The fix was included in a release we did moments ago though, as the timing of this report lined up perfectly with the timing of our release today. Anyone who updates via TestFlight to use V1.0 (Build 20) of Anchor Mobile should now be able to sign msigs and get past this error. 

Edit: Just realized the new release is still pending Apple's review, but should be available soon 👍

**Comment by lukestokes** [comment]
Just tested with the latest version which was released on Testflyte this morning and ti works!

v1.0 (20)
