### ISSUE TITLE
Error registering as a custodian: comparison of assets with different symbols is not allowed

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-client#66]
This may be a contract level error, not sure. My DAC is set up on Jungle with a custom token FIODAC and a custom custodian pay also using FIODAC.

**Comment by lukestokes** [comment]
I noticed it was trying to stake "10.0000 FIODAC" with 4 decimal points but the token is configured for 9.

**Comment by dallasjohnson** [comment]
That's exactly what would cause that error. This is the correct error that you would get from the contract when trying to stake an account incorrect token. In this 9 decimals vs 4 decimals is a different token. While the error message isn't great I'm not sure that it could be handled better in the contract because this is internal to eosio::asset. I think the UI might need to check the decimals.

**Comment by str** [comment]
IMHO, the currency vue component can be modified to always apply the right format/decimals. So if you type 10, or 10.00, the vue component could change that to the decimals for the selected currency.

**Comment by str** [comment]
OK, the code for the asset-input was too complex. I think the changes in brach https://github.com/eosdac/eosdac-client/tree/gh-0066-currency-precision can fix them

Please review and confirm if that fixes the issue.

**Comment by michaeljyeates** [comment]
Found out that this is caused by the config for lockup being set to 4dp.  the vue component is set to be for a certain number of decimal places (and will fix precision to that), rather than the other way around
